//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signant.Common.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPostingStatusResponse", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class GetPostingStatusResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ActivatedField;
        
        private System.DateTime ActiveToDateTimeField;
        
        private System.DateTime CompletedDateTimeField;
        
        private System.DateTime CreatedDateTimeField;
        
        private string DefaultLanguageField;
        
        private string DescriptionField;
        
        private int ErrorCodeField;
        
        private System.DateTime LastModifiedDateTimeField;
        
        private System.DateTime LastReminderDateTimeField;
        
        private string MessageField;
        
        private System.Guid PostingIDField;
        
        private Signant.Global.Common.Enums.PostingTypes PostingTypeField;
        
        private int SignatureCountField;
        
        private Signant.Global.Common.Enums.PostingStatusTypes StatusField;
        
        private bool SuccessField;
        
        private string TitleField;
        
        private int ToBeSignedCountField;
        
        private int TotalDocsReadField;
        
        private int TotalDocsRejectedField;
        
        private int TotalDocsSignedField;
        
        private int TotalDocsToReadField;
        
        private int TotalDocsToSignField;
        
        private int TotalDocsToUploadField;
        
        private int TotalDocsUploadedField;
        
        private System.DateTime WillBeDeletedDateTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activated
        {
            get
            {
                return this.ActivatedField;
            }
            set
            {
                this.ActivatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActiveToDateTime
        {
            get
            {
                return this.ActiveToDateTimeField;
            }
            set
            {
                this.ActiveToDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CompletedDateTime
        {
            get
            {
                return this.CompletedDateTimeField;
            }
            set
            {
                this.CompletedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime
        {
            get
            {
                return this.CreatedDateTimeField;
            }
            set
            {
                this.CreatedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultLanguage
        {
            get
            {
                return this.DefaultLanguageField;
            }
            set
            {
                this.DefaultLanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModifiedDateTime
        {
            get
            {
                return this.LastModifiedDateTimeField;
            }
            set
            {
                this.LastModifiedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastReminderDateTime
        {
            get
            {
                return this.LastReminderDateTimeField;
            }
            set
            {
                this.LastReminderDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PostingID
        {
            get
            {
                return this.PostingIDField;
            }
            set
            {
                this.PostingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Global.Common.Enums.PostingTypes PostingType
        {
            get
            {
                return this.PostingTypeField;
            }
            set
            {
                this.PostingTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SignatureCount
        {
            get
            {
                return this.SignatureCountField;
            }
            set
            {
                this.SignatureCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Global.Common.Enums.PostingStatusTypes Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToBeSignedCount
        {
            get
            {
                return this.ToBeSignedCountField;
            }
            set
            {
                this.ToBeSignedCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDocsRead
        {
            get
            {
                return this.TotalDocsReadField;
            }
            set
            {
                this.TotalDocsReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDocsRejected
        {
            get
            {
                return this.TotalDocsRejectedField;
            }
            set
            {
                this.TotalDocsRejectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDocsSigned
        {
            get
            {
                return this.TotalDocsSignedField;
            }
            set
            {
                this.TotalDocsSignedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDocsToRead
        {
            get
            {
                return this.TotalDocsToReadField;
            }
            set
            {
                this.TotalDocsToReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDocsToSign
        {
            get
            {
                return this.TotalDocsToSignField;
            }
            set
            {
                this.TotalDocsToSignField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDocsToUpload
        {
            get
            {
                return this.TotalDocsToUploadField;
            }
            set
            {
                this.TotalDocsToUploadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDocsUploaded
        {
            get
            {
                return this.TotalDocsUploadedField;
            }
            set
            {
                this.TotalDocsUploadedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WillBeDeletedDateTime
        {
            get
            {
                return this.WillBeDeletedDateTimeField;
            }
            set
            {
                this.WillBeDeletedDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSignPostingStatusDetailsResponse", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class GetSignPostingStatusDetailsResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Signant.Common.Models.StatusDetailsAttachment[] AttachmentsField;
        
        private int ErrorCodeField;
        
        private string MessageField;
        
        private System.Guid PostingIDField;
        
        private bool SuccessField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Common.Models.StatusDetailsAttachment[] Attachments
        {
            get
            {
                return this.AttachmentsField;
            }
            set
            {
                this.AttachmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PostingID
        {
            get
            {
                return this.PostingIDField;
            }
            set
            {
                this.PostingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusDetailsAttachment", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class StatusDetailsAttachment : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid AttachmentIDField;
        
        private Signant.Global.Common.Enums.AttachmentStatus AttachmentStatusField;
        
        private System.Nullable<System.DateTime> CompletedDateTimeField;
        
        private string DescriptionField;
        
        private System.DateTime FileCreatedField;
        
        private string FileHashField;
        
        private System.DateTime FileModifiedField;
        
        private string FileNameField;
        
        private long FileSizeField;
        
        private System.Guid GroupIDField;
        
        private Signant.Common.Models.StatusDetailsRecipient[] RecipientsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AttachmentID
        {
            get
            {
                return this.AttachmentIDField;
            }
            set
            {
                this.AttachmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Global.Common.Enums.AttachmentStatus AttachmentStatus
        {
            get
            {
                return this.AttachmentStatusField;
            }
            set
            {
                this.AttachmentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CompletedDateTime
        {
            get
            {
                return this.CompletedDateTimeField;
            }
            set
            {
                this.CompletedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FileCreated
        {
            get
            {
                return this.FileCreatedField;
            }
            set
            {
                this.FileCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileHash
        {
            get
            {
                return this.FileHashField;
            }
            set
            {
                this.FileHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FileModified
        {
            get
            {
                return this.FileModifiedField;
            }
            set
            {
                this.FileModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FileSize
        {
            get
            {
                return this.FileSizeField;
            }
            set
            {
                this.FileSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GroupID
        {
            get
            {
                return this.GroupIDField;
            }
            set
            {
                this.GroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Common.Models.StatusDetailsRecipient[] Recipients
        {
            get
            {
                return this.RecipientsField;
            }
            set
            {
                this.RecipientsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusDetailsRecipient", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class StatusDetailsRecipient : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ActionLastDateTimeField;
        
        private Signant.Global.Common.Enums.ActionStatus ActionStatusField;
        
        private Signant.Global.Common.Enums.ActionType ActionTypeField;
        
        private System.Nullable<System.DateTime> CompletedDateTimeField;
        
        private string EmailField;
        
        private System.Nullable<System.DateTime> LastReminderDateTimeField;
        
        private string MobileNumberField;
        
        private string NameField;
        
        private bool ReadField;
        
        private System.Guid RecipientIDField;
        
        private string RejectReasonField;
        
        private bool RejectedField;
        
        private string SignatureURLField;
        
        private bool SignedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActionLastDateTime
        {
            get
            {
                return this.ActionLastDateTimeField;
            }
            set
            {
                this.ActionLastDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Global.Common.Enums.ActionStatus ActionStatus
        {
            get
            {
                return this.ActionStatusField;
            }
            set
            {
                this.ActionStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Global.Common.Enums.ActionType ActionType
        {
            get
            {
                return this.ActionTypeField;
            }
            set
            {
                this.ActionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CompletedDateTime
        {
            get
            {
                return this.CompletedDateTimeField;
            }
            set
            {
                this.CompletedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastReminderDateTime
        {
            get
            {
                return this.LastReminderDateTimeField;
            }
            set
            {
                this.LastReminderDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Read
        {
            get
            {
                return this.ReadField;
            }
            set
            {
                this.ReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RecipientID
        {
            get
            {
                return this.RecipientIDField;
            }
            set
            {
                this.RecipientIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RejectReason
        {
            get
            {
                return this.RejectReasonField;
            }
            set
            {
                this.RejectReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Rejected
        {
            get
            {
                return this.RejectedField;
            }
            set
            {
                this.RejectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureURL
        {
            get
            {
                return this.SignatureURLField;
            }
            set
            {
                this.SignatureURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Signed
        {
            get
            {
                return this.SignedField;
            }
            set
            {
                this.SignedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeletePostingResponse", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class DeletePostingResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorCodeField;
        
        private string MessageField;
        
        private bool SuccessField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Posting", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class Posting : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> ActiveFromField;
        
        private System.DateTime ActiveToField;
        
        private Signant.Common.Models.Attachment[] AttachmentsField;
        
        private bool AutoActivateField;
        
        private string ConsumerInvoiceInfoField;
        
        private string ConsumerNameField;
        
        private string ConsumerOrderInvoiceInfoField;
        
        private string ConsumerOrderOrgNameField;
        
        private string ConsumerOrderOrgNoField;
        
        private string ConsumerOrgNoField;
        
        private string DescriptionField;
        
        private string DistributorSystemIDField;
        
        private System.Nullable<System.DateTime> NotificationStartField;
        
        private Signant.Common.Models.PostingAdmin[] PostingAdminsField;
        
        private Signant.Common.Models.Recipient[] RecipientsField;
        
        private string SenderNameField;
        
        private string TitleField;
        
        private bool UseWidgetField;
        
        private bool UseWidgetOnAllPagesField;
        
        private System.Nullable<Signant.Global.Common.Enums.WidgetLocationDirection> WidgetLocationDirectionField;
        
        private System.DateTime WillBeDeletedDateTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ActiveFrom
        {
            get
            {
                return this.ActiveFromField;
            }
            set
            {
                this.ActiveFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActiveTo
        {
            get
            {
                return this.ActiveToField;
            }
            set
            {
                this.ActiveToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Common.Models.Attachment[] Attachments
        {
            get
            {
                return this.AttachmentsField;
            }
            set
            {
                this.AttachmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AutoActivate
        {
            get
            {
                return this.AutoActivateField;
            }
            set
            {
                this.AutoActivateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerInvoiceInfo
        {
            get
            {
                return this.ConsumerInvoiceInfoField;
            }
            set
            {
                this.ConsumerInvoiceInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerName
        {
            get
            {
                return this.ConsumerNameField;
            }
            set
            {
                this.ConsumerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerOrderInvoiceInfo
        {
            get
            {
                return this.ConsumerOrderInvoiceInfoField;
            }
            set
            {
                this.ConsumerOrderInvoiceInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerOrderOrgName
        {
            get
            {
                return this.ConsumerOrderOrgNameField;
            }
            set
            {
                this.ConsumerOrderOrgNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerOrderOrgNo
        {
            get
            {
                return this.ConsumerOrderOrgNoField;
            }
            set
            {
                this.ConsumerOrderOrgNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerOrgNo
        {
            get
            {
                return this.ConsumerOrgNoField;
            }
            set
            {
                this.ConsumerOrgNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributorSystemID
        {
            get
            {
                return this.DistributorSystemIDField;
            }
            set
            {
                this.DistributorSystemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NotificationStart
        {
            get
            {
                return this.NotificationStartField;
            }
            set
            {
                this.NotificationStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Common.Models.PostingAdmin[] PostingAdmins
        {
            get
            {
                return this.PostingAdminsField;
            }
            set
            {
                this.PostingAdminsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Common.Models.Recipient[] Recipients
        {
            get
            {
                return this.RecipientsField;
            }
            set
            {
                this.RecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderName
        {
            get
            {
                return this.SenderNameField;
            }
            set
            {
                this.SenderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseWidget
        {
            get
            {
                return this.UseWidgetField;
            }
            set
            {
                this.UseWidgetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseWidgetOnAllPages
        {
            get
            {
                return this.UseWidgetOnAllPagesField;
            }
            set
            {
                this.UseWidgetOnAllPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Signant.Global.Common.Enums.WidgetLocationDirection> WidgetLocationDirection
        {
            get
            {
                return this.WidgetLocationDirectionField;
            }
            set
            {
                this.WidgetLocationDirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WillBeDeletedDateTime
        {
            get
            {
                return this.WillBeDeletedDateTimeField;
            }
            set
            {
                this.WillBeDeletedDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachment", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class Attachment : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Signant.Global.Common.Enums.ActionType ActionTypeField;
        
        private string DescriptionField;
        
        private byte[] FileField;
        
        private string FileNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Global.Common.Enums.ActionType ActionType
        {
            get
            {
                return this.ActionTypeField;
            }
            set
            {
                this.ActionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] File
        {
            get
            {
                return this.FileField;
            }
            set
            {
                this.FileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostingAdmin", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class PostingAdmin : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailField;
        
        private string MobileNumberField;
        
        private string NameField;
        
        private System.Nullable<bool> NotifyByEmailField;
        
        private string SSNField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> NotifyByEmail
        {
            get
            {
                return this.NotifyByEmailField;
            }
            set
            {
                this.NotifyByEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSN
        {
            get
            {
                return this.SSNField;
            }
            set
            {
                this.SSNField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipient", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class Recipient : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ActionStatusField;
        
        private string EmailField;
        
        private string IconStatusField;
        
        private string MobileNumberField;
        
        private string NameField;
        
        private System.Nullable<bool> NotifyByEmailField;
        
        private int PriorityField;
        
        private System.Nullable<bool> RejectedField;
        
        private string SSNField;
        
        private System.Nullable<bool> SignedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionStatus
        {
            get
            {
                return this.ActionStatusField;
            }
            set
            {
                this.ActionStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IconStatus
        {
            get
            {
                return this.IconStatusField;
            }
            set
            {
                this.IconStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> NotifyByEmail
        {
            get
            {
                return this.NotifyByEmailField;
            }
            set
            {
                this.NotifyByEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Rejected
        {
            get
            {
                return this.RejectedField;
            }
            set
            {
                this.RejectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSN
        {
            get
            {
                return this.SSNField;
            }
            set
            {
                this.SSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Signed
        {
            get
            {
                return this.SignedField;
            }
            set
            {
                this.SignedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateSignPostingResponse", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class CreateSignPostingResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ActivationUrlField;
        
        private Signant.Common.Models.AttachmentInfo[] AttachmentInfosField;
        
        private int ErrorCodeField;
        
        private string MessageField;
        
        private System.Guid PostingIDField;
        
        private bool SuccessField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivationUrl
        {
            get
            {
                return this.ActivationUrlField;
            }
            set
            {
                this.ActivationUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Common.Models.AttachmentInfo[] AttachmentInfos
        {
            get
            {
                return this.AttachmentInfosField;
            }
            set
            {
                this.AttachmentInfosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PostingID
        {
            get
            {
                return this.PostingIDField;
            }
            set
            {
                this.PostingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentInfo", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class AttachmentInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid AttachmentIDField;
        
        private string DescriptionField;
        
        private string FileNameField;
        
        private System.Guid GroupIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AttachmentID
        {
            get
            {
                return this.AttachmentIDField;
            }
            set
            {
                this.AttachmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GroupID
        {
            get
            {
                return this.GroupIDField;
            }
            set
            {
                this.GroupIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadAttachmentResponse", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class DownloadAttachmentResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] AttachmentFileField;
        
        private System.Guid AttachmentIDField;
        
        private string DescriptionField;
        
        private int ErrorCodeField;
        
        private string FileHashField;
        
        private string FileNameField;
        
        private string MessageField;
        
        private bool SuccessField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] AttachmentFile
        {
            get
            {
                return this.AttachmentFileField;
            }
            set
            {
                this.AttachmentFileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AttachmentID
        {
            get
            {
                return this.AttachmentIDField;
            }
            set
            {
                this.AttachmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileHash
        {
            get
            {
                return this.FileHashField;
            }
            set
            {
                this.FileHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAuthenticationTokenResponse", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class GetAuthenticationTokenResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool AuthenticatedField;
        
        private bool AuthenticationFailedField;
        
        private int ErrorCodeField;
        
        private string MessageField;
        
        private bool SuccessField;
        
        private bool TokenExpiredField;
        
        private string URLField;
        
        private Signant.Common.Models.UserToken UserTokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Authenticated
        {
            get
            {
                return this.AuthenticatedField;
            }
            set
            {
                this.AuthenticatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AuthenticationFailed
        {
            get
            {
                return this.AuthenticationFailedField;
            }
            set
            {
                this.AuthenticationFailedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TokenExpired
        {
            get
            {
                return this.TokenExpiredField;
            }
            set
            {
                this.TokenExpiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL
        {
            get
            {
                return this.URLField;
            }
            set
            {
                this.URLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Common.Models.UserToken UserToken
        {
            get
            {
                return this.UserTokenField;
            }
            set
            {
                this.UserTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserToken", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class UserToken : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Signant.Global.Common.Enums.AuthenticationLevels AuthenticationLevelField;
        
        private System.Guid TokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Signant.Global.Common.Enums.AuthenticationLevels AuthenticationLevel
        {
            get
            {
                return this.AuthenticationLevelField;
            }
            set
            {
                this.AuthenticationLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserInfoByTokenIDResponse", Namespace="http://schemas.datacontract.org/2004/07/Signant.Common.Models")]
    public partial class GetUserInfoByTokenIDResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorCodeField;
        
        private string MessageField;
        
        private bool SuccessField;
        
        private int TokenAuthLevelField;
        
        private System.Nullable<System.DateTime> TokenExpireDateTimeField;
        
        private bool TokenExpiredField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TokenAuthLevel
        {
            get
            {
                return this.TokenAuthLevelField;
            }
            set
            {
                this.TokenAuthLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TokenExpireDateTime
        {
            get
            {
                return this.TokenExpireDateTimeField;
            }
            set
            {
                this.TokenExpireDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TokenExpired
        {
            get
            {
                return this.TokenExpiredField;
            }
            set
            {
                this.TokenExpiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
}
namespace Signant.Global.Common.Enums
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostingTypes", Namespace="http://schemas.datacontract.org/2004/07/Signant.Global.Common.Enums")]
    public enum PostingTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SignViewDocument = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestDocument = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SignOwnDocument = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SignViewDocumentWithOwner = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantSign = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostingStatusTypes", Namespace="http://schemas.datacontract.org/2004/07/Signant.Global.Common.Enums")]
    public enum PostingStatusTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompletedPartially = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentStatus", Namespace="http://schemas.datacontract.org/2004/07/Signant.Global.Common.Enums")]
    public enum AttachmentStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionStatus", Namespace="http://schemas.datacontract.org/2004/07/Signant.Global.Common.Enums")]
    public enum ActionStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delayed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionType", Namespace="http://schemas.datacontract.org/2004/07/Signant.Global.Common.Enums")]
    public enum ActionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sign = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WidgetLocationDirection", Namespace="http://schemas.datacontract.org/2004/07/Signant.Global.Common.Enums")]
    public enum WidgetLocationDirection : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Right_TopToBottom = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Left_TopToBottom = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Top_RightToLeft = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Top_LeftToRight = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bottom_RightToLeft = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bottom_LeftToRight = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationLevels", Namespace="http://schemas.datacontract.org/2004/07/Signant.Global.Common.Enums")]
    public enum AuthenticationLevels : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Level0 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Level1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Level2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Level3 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Level4 = 4,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPostingsService")]
public interface IPostingsService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/GetPostingStatus", ReplyAction="http://tempuri.org/IPostingsService/GetPostingStatusResponse")]
    Signant.Common.Models.GetPostingStatusResponse GetPostingStatus(string DistributorID, string AccessCode, System.Guid PostingID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/GetPostingStatus", ReplyAction="http://tempuri.org/IPostingsService/GetPostingStatusResponse")]
    System.Threading.Tasks.Task<Signant.Common.Models.GetPostingStatusResponse> GetPostingStatusAsync(string DistributorID, string AccessCode, System.Guid PostingID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/GetSignPostingStatusDetails", ReplyAction="http://tempuri.org/IPostingsService/GetSignPostingStatusDetailsResponse")]
    Signant.Common.Models.GetSignPostingStatusDetailsResponse GetSignPostingStatusDetails(string DistributorID, string AccessCode, System.Guid PostingID, string AccessToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/GetSignPostingStatusDetails", ReplyAction="http://tempuri.org/IPostingsService/GetSignPostingStatusDetailsResponse")]
    System.Threading.Tasks.Task<Signant.Common.Models.GetSignPostingStatusDetailsResponse> GetSignPostingStatusDetailsAsync(string DistributorID, string AccessCode, System.Guid PostingID, string AccessToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/GetSignPostingStatusDetailsV2", ReplyAction="http://tempuri.org/IPostingsService/GetSignPostingStatusDetailsV2Response")]
    Signant.Common.Models.GetSignPostingStatusDetailsResponse GetSignPostingStatusDetailsV2(string DistributorID, string AccessCode, System.Guid PostingID, string AccessToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/GetSignPostingStatusDetailsV2", ReplyAction="http://tempuri.org/IPostingsService/GetSignPostingStatusDetailsV2Response")]
    System.Threading.Tasks.Task<Signant.Common.Models.GetSignPostingStatusDetailsResponse> GetSignPostingStatusDetailsV2Async(string DistributorID, string AccessCode, System.Guid PostingID, string AccessToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/DeletePosting", ReplyAction="http://tempuri.org/IPostingsService/DeletePostingResponse")]
    Signant.Common.Models.DeletePostingResponse DeletePosting(string DistributorID, string AccessCode, System.Guid PostingID, string AccessToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/DeletePosting", ReplyAction="http://tempuri.org/IPostingsService/DeletePostingResponse")]
    System.Threading.Tasks.Task<Signant.Common.Models.DeletePostingResponse> DeletePostingAsync(string DistributorID, string AccessCode, System.Guid PostingID, string AccessToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/CreateSignPosting", ReplyAction="http://tempuri.org/IPostingsService/CreateSignPostingResponse")]
    Signant.Common.Models.CreateSignPostingResponse CreateSignPosting(string DistributorID, string AccessCode, Signant.Common.Models.Posting SignPosting);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/CreateSignPosting", ReplyAction="http://tempuri.org/IPostingsService/CreateSignPostingResponse")]
    System.Threading.Tasks.Task<Signant.Common.Models.CreateSignPostingResponse> CreateSignPostingAsync(string DistributorID, string AccessCode, Signant.Common.Models.Posting SignPosting);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/CreateSignPostingWithToken", ReplyAction="http://tempuri.org/IPostingsService/CreateSignPostingWithTokenResponse")]
    Signant.Common.Models.CreateSignPostingResponse CreateSignPostingWithToken(string DistributorID, string AccessCode, Signant.Common.Models.Posting SignPosting, string AccessToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/CreateSignPostingWithToken", ReplyAction="http://tempuri.org/IPostingsService/CreateSignPostingWithTokenResponse")]
    System.Threading.Tasks.Task<Signant.Common.Models.CreateSignPostingResponse> CreateSignPostingWithTokenAsync(string DistributorID, string AccessCode, Signant.Common.Models.Posting SignPosting, string AccessToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/DownloadAttachment", ReplyAction="http://tempuri.org/IPostingsService/DownloadAttachmentResponse")]
    Signant.Common.Models.DownloadAttachmentResponse DownloadAttachment(string DistributorID, string AccessCode, System.Guid PostingID, System.Guid AttachmentID, string AccessToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/DownloadAttachment", ReplyAction="http://tempuri.org/IPostingsService/DownloadAttachmentResponse")]
    System.Threading.Tasks.Task<Signant.Common.Models.DownloadAttachmentResponse> DownloadAttachmentAsync(string DistributorID, string AccessCode, System.Guid PostingID, System.Guid AttachmentID, string AccessToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/GetAuthenticationToken", ReplyAction="http://tempuri.org/IPostingsService/GetAuthenticationTokenResponse")]
    Signant.Common.Models.GetAuthenticationTokenResponse GetAuthenticationToken(System.Guid TokenRequestID, Signant.Global.Common.Enums.AuthenticationLevels AuthenticationLevelID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/GetAuthenticationToken", ReplyAction="http://tempuri.org/IPostingsService/GetAuthenticationTokenResponse")]
    System.Threading.Tasks.Task<Signant.Common.Models.GetAuthenticationTokenResponse> GetAuthenticationTokenAsync(System.Guid TokenRequestID, Signant.Global.Common.Enums.AuthenticationLevels AuthenticationLevelID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/GetUserInfoByTokenID", ReplyAction="http://tempuri.org/IPostingsService/GetUserInfoByTokenIDResponse")]
    Signant.Common.Models.GetUserInfoByTokenIDResponse GetUserInfoByTokenID(System.Guid userToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostingsService/GetUserInfoByTokenID", ReplyAction="http://tempuri.org/IPostingsService/GetUserInfoByTokenIDResponse")]
    System.Threading.Tasks.Task<Signant.Common.Models.GetUserInfoByTokenIDResponse> GetUserInfoByTokenIDAsync(System.Guid userToken);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IPostingsServiceChannel : IPostingsService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PostingsServiceClient : System.ServiceModel.ClientBase<IPostingsService>, IPostingsService
{
    
    public PostingsServiceClient()
    {
    }
    
    public PostingsServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PostingsServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PostingsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PostingsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Signant.Common.Models.GetPostingStatusResponse GetPostingStatus(string DistributorID, string AccessCode, System.Guid PostingID)
    {
        return base.Channel.GetPostingStatus(DistributorID, AccessCode, PostingID);
    }
    
    public System.Threading.Tasks.Task<Signant.Common.Models.GetPostingStatusResponse> GetPostingStatusAsync(string DistributorID, string AccessCode, System.Guid PostingID)
    {
        return base.Channel.GetPostingStatusAsync(DistributorID, AccessCode, PostingID);
    }
    
    public Signant.Common.Models.GetSignPostingStatusDetailsResponse GetSignPostingStatusDetails(string DistributorID, string AccessCode, System.Guid PostingID, string AccessToken)
    {
        return base.Channel.GetSignPostingStatusDetails(DistributorID, AccessCode, PostingID, AccessToken);
    }
    
    public System.Threading.Tasks.Task<Signant.Common.Models.GetSignPostingStatusDetailsResponse> GetSignPostingStatusDetailsAsync(string DistributorID, string AccessCode, System.Guid PostingID, string AccessToken)
    {
        return base.Channel.GetSignPostingStatusDetailsAsync(DistributorID, AccessCode, PostingID, AccessToken);
    }
    
    public Signant.Common.Models.GetSignPostingStatusDetailsResponse GetSignPostingStatusDetailsV2(string DistributorID, string AccessCode, System.Guid PostingID, string AccessToken)
    {
        return base.Channel.GetSignPostingStatusDetailsV2(DistributorID, AccessCode, PostingID, AccessToken);
    }
    
    public System.Threading.Tasks.Task<Signant.Common.Models.GetSignPostingStatusDetailsResponse> GetSignPostingStatusDetailsV2Async(string DistributorID, string AccessCode, System.Guid PostingID, string AccessToken)
    {
        return base.Channel.GetSignPostingStatusDetailsV2Async(DistributorID, AccessCode, PostingID, AccessToken);
    }
    
    public Signant.Common.Models.DeletePostingResponse DeletePosting(string DistributorID, string AccessCode, System.Guid PostingID, string AccessToken)
    {
        return base.Channel.DeletePosting(DistributorID, AccessCode, PostingID, AccessToken);
    }
    
    public System.Threading.Tasks.Task<Signant.Common.Models.DeletePostingResponse> DeletePostingAsync(string DistributorID, string AccessCode, System.Guid PostingID, string AccessToken)
    {
        return base.Channel.DeletePostingAsync(DistributorID, AccessCode, PostingID, AccessToken);
    }
    
    public Signant.Common.Models.CreateSignPostingResponse CreateSignPosting(string DistributorID, string AccessCode, Signant.Common.Models.Posting SignPosting)
    {
        return base.Channel.CreateSignPosting(DistributorID, AccessCode, SignPosting);
    }
    
    public System.Threading.Tasks.Task<Signant.Common.Models.CreateSignPostingResponse> CreateSignPostingAsync(string DistributorID, string AccessCode, Signant.Common.Models.Posting SignPosting)
    {
        return base.Channel.CreateSignPostingAsync(DistributorID, AccessCode, SignPosting);
    }
    
    public Signant.Common.Models.CreateSignPostingResponse CreateSignPostingWithToken(string DistributorID, string AccessCode, Signant.Common.Models.Posting SignPosting, string AccessToken)
    {
        return base.Channel.CreateSignPostingWithToken(DistributorID, AccessCode, SignPosting, AccessToken);
    }
    
    public System.Threading.Tasks.Task<Signant.Common.Models.CreateSignPostingResponse> CreateSignPostingWithTokenAsync(string DistributorID, string AccessCode, Signant.Common.Models.Posting SignPosting, string AccessToken)
    {
        return base.Channel.CreateSignPostingWithTokenAsync(DistributorID, AccessCode, SignPosting, AccessToken);
    }
    
    public Signant.Common.Models.DownloadAttachmentResponse DownloadAttachment(string DistributorID, string AccessCode, System.Guid PostingID, System.Guid AttachmentID, string AccessToken)
    {
        return base.Channel.DownloadAttachment(DistributorID, AccessCode, PostingID, AttachmentID, AccessToken);
    }
    
    public System.Threading.Tasks.Task<Signant.Common.Models.DownloadAttachmentResponse> DownloadAttachmentAsync(string DistributorID, string AccessCode, System.Guid PostingID, System.Guid AttachmentID, string AccessToken)
    {
        return base.Channel.DownloadAttachmentAsync(DistributorID, AccessCode, PostingID, AttachmentID, AccessToken);
    }
    
    public Signant.Common.Models.GetAuthenticationTokenResponse GetAuthenticationToken(System.Guid TokenRequestID, Signant.Global.Common.Enums.AuthenticationLevels AuthenticationLevelID)
    {
        return base.Channel.GetAuthenticationToken(TokenRequestID, AuthenticationLevelID);
    }
    
    public System.Threading.Tasks.Task<Signant.Common.Models.GetAuthenticationTokenResponse> GetAuthenticationTokenAsync(System.Guid TokenRequestID, Signant.Global.Common.Enums.AuthenticationLevels AuthenticationLevelID)
    {
        return base.Channel.GetAuthenticationTokenAsync(TokenRequestID, AuthenticationLevelID);
    }
    
    public Signant.Common.Models.GetUserInfoByTokenIDResponse GetUserInfoByTokenID(System.Guid userToken)
    {
        return base.Channel.GetUserInfoByTokenID(userToken);
    }
    
    public System.Threading.Tasks.Task<Signant.Common.Models.GetUserInfoByTokenIDResponse> GetUserInfoByTokenIDAsync(System.Guid userToken)
    {
        return base.Channel.GetUserInfoByTokenIDAsync(userToken);
    }
}
